### ISSUE TITLE
User cannot advance past login messaging with Safari web browser

### ISSUE THREAD

**Issue by ghost** [18F/cg-uaa#19]
At login.fr.cloud.gov, clicking "AGREE AND CONTINUE" does nothing in the Safari web browser; the user cannot advance.

**Comment by msecret** [comment]
I believe this was fixed

**Comment by ghost** [comment]
This is not fixed.  Neither the "AGREE AND CONTINUE" nor the "Hide details" (after clicking Read more details) buttons work.  The dismiss "X" does not work either.
